services:
  - type: web
    name: salao-online
    env: node
    buildCommand: chmod +x build-render.sh && ./build-render.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.16.0
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY_LIVE
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY_LIVE
        sync: false
      - key: STRIPE_WEBHOOK_SECRET_LIVE
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        sync: false
      - key: PROFESSIONAL_SMTP_HOST
        sync: false
      - key: PROFESSIONAL_SMTP_PORT
        sync: false
      - key: PROFESSIONAL_SMTP_USER
        sync: false
      - key: PROFESSIONAL_SMTP_PASS
        sync: false
      - key: BASE_URL
        sync: false
